# Generated by Django 4.2.15 on 2024-08-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('work_experience', models.IntegerField()),
                ('union_membership', models.BooleanField(default=False)),
                ('political_party_membership', models.BooleanField(default=False)),
                ('hire_date', models.DateField()),
                ('disability', models.BooleanField(default=False)),
                ('occupational_disease', models.BooleanField(default=False)),
            ],
        ),
    ]
