# Generated by Django 4.2.15 on 2024-08-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
