# Generated by Django 4.2.15 on 2024-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_hire_date_employee_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='disability',
            field=models.CharField(choices=[('-', 'Нет'), ('1', '1 группа'), ('2', '2 группа'), ('3', '3 группа')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='occupational_disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='political_party_membership',
            field=models.TextField(blank=True, null=True),
        ),
    ]
