# Generated by Django 4.2.15 on 2024-08-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_disability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='occupational_disease',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='political_party_membership',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
