# Generated by Django 4.2.15 on 2024-09-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_occupational_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='disability',
            field=models.CharField(choices=[('-', 'Нет'), ('1', '1 группа'), ('2', '2 группа'), ('3', '3 группа')], default='-', max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(max_length=100, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='occupational_disease',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессиональное заболевание'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='political_party_membership',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Членство в политической партии'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(max_length=100, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='union_membership',
            field=models.BooleanField(default=False, verbose_name='Членство в профсоюзе'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_experience',
            field=models.IntegerField(verbose_name='Стаж работы'),
        ),
    ]
