# Generated by Django 4.2.15 on 2024-10-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_manager_alter_employee_options_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Отделение'),
        ),
    ]
