# Generated by Django 4.2.15 on 2024-10-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_options_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Заведующего', 'verbose_name_plural': 'Заведующие отделами'},
        ),
        migrations.AlterField(
            model_name='manager',
            name='employees',
            field=models.ManyToManyField(related_name='managers', to='employees.employee', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'qualification': 'Менеджер проектов'}, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Руководитель'),
        ),
    ]
