# Generated by Django 4.2.15 on 2024-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_employee_disability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default='2000', verbose_name='Заработная плата, BYN'),
        ),
    ]
